package Ventanas;

import JavaClases.*;
import java.awt.*;
import java.util.*;
import javax.swing.border.*;

/**
 * [Login] Clase de interfaz GUI de usuario y contraseña que permite acceder a la interfaz Menu
 * @since 24/11/2017
 * @version 2.0
 * @author Julian Andres Castaño - 1625743
 */

public class Login extends javax.swing.JFrame {
     
    //Declaracion de variables estaticas
    public static Border bordeNegro;
    public static Image iconoVentana; 
    
    //Declaracion de variables de clase
    private Validaciones validacionTotal;
    private String matrizUsuarios[][]={{"admin","123"},{"root","345"}};

//=======================================================================================================   
    /**
    * Constructor de la clase Login
    * @since Login.java
    */ 
    
    public Login() 
    {
        initComponents();
        
        //Inicializacion de variables
        validacionTotal = new Validaciones();
        bordeNegro = new EtchedBorder(30,Color.black, Color.white);        
        iconoVentana = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Menu/logoMinimo.png"));     
        
        //Implementacion de ajustes
        ajustesGraficos();

    }
    
//=======================================================================================================
    /**
     * Metodo que realiza ajustes visuales a la interfaz
     */
    public final void ajustesGraficos()
    {        
        this.setLocationRelativeTo(null); 
        this.setIconImage(iconoVentana);
        this.getRootPane().setBorder(bordeNegro);
        jLabelTitulo.requestFocus();
          
    }
//======================================================================================================= 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPpal = new javax.swing.JPanel();
        jPanelContain = new javax.swing.JPanel();
        jPanelLogin = new javax.swing.JPanel();
        jSeparatorUsuario = new javax.swing.JSeparator();
        jSeparatorContraseña = new javax.swing.JSeparator();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelimgPassword = new javax.swing.JLabel();
        jLabelimgUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonLogin = new java.awt.Button();
        jPanelBuffer = new javax.swing.JPanel();
        jLabelimgBuffer = new javax.swing.JLabel();
        jLabelBuffer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanelPpal.setBackground(new java.awt.Color(255, 255, 255));

        jPanelContain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContain.setLayout(new java.awt.CardLayout());

        jPanelLogin.setBackground(new java.awt.Color(255, 255, 255));

        jSeparatorUsuario.setBackground(new java.awt.Color(41, 128, 185));
        jSeparatorUsuario.setForeground(new java.awt.Color(41, 128, 185));

        jSeparatorContraseña.setBackground(new java.awt.Color(41, 128, 185));
        jSeparatorContraseña.setForeground(new java.awt.Color(41, 128, 185));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitulo.setText("Login");

        jLabelCerrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabelCerrar.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("X");
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCerrarMousePressed(evt);
            }
        });

        jLabelimgPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login/contrasena.png"))); // NOI18N
        jLabelimgPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelimgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login/usuario.png"))); // NOI18N

        jTextFieldUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldUsuario.setText("Usuario");
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
        });

        jPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(102, 102, 102));
        jPassword.setText("jPasswordField1");
        jPassword.setBorder(null);
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
        });

        jButtonLogin.setBackground(new java.awt.Color(41, 128, 185));
        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setLabel("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabelTitulo))
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabelimgUsuario)
                .addGap(12, 12, 12)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparatorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addComponent(jLabelimgPassword)
                        .addGap(12, 12, 12)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparatorContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addComponent(jLabelCerrar)
                .addGap(64, 64, 64)
                .addComponent(jLabelTitulo)
                .addGap(59, 59, 59)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelimgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparatorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelimgPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jSeparatorContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanelContain.add(jPanelLogin, "card2");

        jPanelBuffer.setBackground(new java.awt.Color(255, 255, 255));

        jLabelimgBuffer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login/buffer.gif"))); // NOI18N

        jLabelBuffer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBuffer.setForeground(new java.awt.Color(41, 128, 185));
        jLabelBuffer.setText("Ingresando...");

        javax.swing.GroupLayout jPanelBufferLayout = new javax.swing.GroupLayout(jPanelBuffer);
        jPanelBuffer.setLayout(jPanelBufferLayout);
        jPanelBufferLayout.setHorizontalGroup(
            jPanelBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBufferLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanelBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelimgBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBuffer))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanelBufferLayout.setVerticalGroup(
            jPanelBufferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBufferLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabelimgBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelBuffer)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jPanelContain.add(jPanelBuffer, "card2");

        javax.swing.GroupLayout jPanelPpalLayout = new javax.swing.GroupLayout(jPanelPpal);
        jPanelPpal.setLayout(jPanelPpalLayout);
        jPanelPpalLayout.setHorizontalGroup(
            jPanelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPpalLayout.setVerticalGroup(
            jPanelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        
        String password = new String (jPassword.getPassword());
        String usuario = jTextFieldUsuario.getText();
        String arregloValidar[] = {usuario, password};
        boolean habilitado = false;
        
        if (!(validacionTotal.validarExcepciones(arregloValidar, 2, 0, 0).equals("")))
        {
            new jAdvertencia(this, true,validacionTotal.validarExcepciones(arregloValidar, 2, 0, 0)).setVisible(true);                 
        }
        
        else
        {

            for (String[] matriz1 : matrizUsuarios) {
                for (int j = 0; j<matrizUsuarios.length; j++) {
                    if (usuario.equals(matriz1[j]) && (password.equals(matriz1[j+1]))) {
                        habilitado=true;
                    }
                }
            }
 
            if (habilitado==true)
            {
                jPanelLogin.setVisible(false);
                jPanelBuffer.setVisible(true);
                new java.util.Timer().schedule(new TimerTask() {
                @Override
                public void run() 
                {   
                    new Menu().setVisible(true);
                    //dispose();
                }
                },1000*2);
            }

            else
            {
                new jAdvertencia(this, true,"El usuario o contraseña son incorrectos").setVisible(true);
                jTextFieldUsuario.setText("");
                jPassword.setText("");
                jTextFieldUsuario.requestFocus();
            }   
        }
      
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        jTextFieldUsuario.setText("");
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        jPassword.setText("");
    }//GEN-LAST:event_jPasswordFocusGained

    private void jLabelCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabelCerrarMousePressed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
   
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button jButtonLogin;
    private javax.swing.JLabel jLabelBuffer;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelimgBuffer;
    private javax.swing.JLabel jLabelimgPassword;
    private javax.swing.JLabel jLabelimgUsuario;
    private javax.swing.JPanel jPanelBuffer;
    private javax.swing.JPanel jPanelContain;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelPpal;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparatorContraseña;
    private javax.swing.JSeparator jSeparatorUsuario;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}


